
<?php if ($this->getHelperData()->isEnabled()): ?>
<?php
$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

?>
<section class="fifth-slider">
    <div class="mp-product-slider-title">
        <p><span><?php echo  __($this->getTitle())?></span></p>
    </div>
    <?php if (count($_productCollection)): ?>
    <div id="fifth-product-slider" class="owl-carousel owl-theme">

        <?php foreach ($_productCollection as $product): ?>
            <?php
            $_item = $block->getProductById($product->getId());
            ?>

            <div class="product-item-info item ">

                <div class="product details product-item-details">

                    <?php
                    $imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
                    $productImage = $imageBlock->getImage($_item, 'category_page_grid');  /* $product pass product object here */
                    ?>
                    <div class="image">  <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                            <?php  echo $productImage->toHtml(); ?>
                        </a>
                    </div>
                    <strong class="product name product-item-name">
                        <a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                           href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                            <?php echo $block->escapeHtml($_item->getName()) ?></a>
                    </strong>
                </div>
                <div class="product actions product-item-actions">
                    <div class="actions-primary">
                        <?php if ($_item->getIsSalable()): ?>
                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                </button>
                            <?php else: ?>
                                <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                ?>
                                <button class="action tocart primary"
                                        data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                </button>
                            <?php endif; ?>
                        <?php endif; ?>

                    </div>
                </div>
            </div>

        <?php endforeach; ?>

    </div>
    <?php else: ?>

      <div class="message warning" >   <p><?php /* @escapeNotVerified */ echo __('There is no product to show') ?></p></div>
    <?php endif; ?>
</section>
<?php echo $block->getJsPart(); ?>
<?php else: ?>
    <p><?php /* @escapeNotVerified */ echo __('Please enable Slider') ?></p>
<?php endif; ?>
